

micronaut.application.name=java25-serverless-risk-engine

riskengine.dynamodb.table-name=${RISKENGINE_DYNAMODB_TABLE_NAME:RiskEvents}
riskengine.dynamodb.endpoint=${RISKENGINE_DYNAMODB_ENDPOINT:http://localhost:8000}
riskengine.dynamodb.region=${RISKENGINE_DYNAMODB_REGION:us-east-1}
